# Generated by Django 4.2.4 on 2023-09-04 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('traductor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Translation',
        ),
        migrations.RemoveField(
            model_name='busqueda',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='historialtraduccion',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='historialtraduccion',
            name='traduccion',
        ),
        migrations.RemoveField(
            model_name='historialtraduccion',
            name='usuario',
        ),
        migrations.AddField(
            model_name='historialtraduccion',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='historialtraduccion',
            name='texto_original',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='historialtraduccion',
            name='texto_traducido',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='traduccion',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
